apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-satisfaction-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: customer-satisfaction-api-deployment
  template:
    metadata:
      labels:
        app: customer-satisfaction-api-deployment
    spec:
      containers:
        - name: customer-satisfaction-api
          image: elghibaomar/customer-satisfaction-api:latest
          env:
            - name: PORT
              value: "8000"
          ports:
          - containerPort: 8000


---
apiVersion: v1
kind: Service
metadata:
  name: customer-satisfaction-api-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: customer-satisfaction-api-deployment






