apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-engagement-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-engagement-deployment
  template:
    metadata:
      labels:
        app: fastapi-engagement-deployment
    spec:
      containers:
        - name: fastapi-engagement
          image: elghibaomar/fastapi-engagement:latest
          env:
            - name: PORT
              value: "8181"
          ports:
            - containerPort: 8181


---

apiVersion: v1
kind: Service
metadata:
  name: fastapi-engagement-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8181
  selector:
    app: fastapi-engagement-deployment